### ISSUE TITLE
加到XX-Net的wiki里去了

### ISSUE THREAD

**Issue by dou4cc** [KenOokamiHoro/it_have_not_get_a_name_yet#4]
毕竟是入门读物（

https://github.com/XX-net/XX-Net/wiki/%E6%8B%A5%E6%8A%B1%E8%87%AA%E7%94%B1%E8%BD%AF%E4%BB%B6

**Comment by KenOokamiHoro** [comment]
:see_no_evil: 其实等完成度再高一点再放也不迟……
