### ISSUE TITLE
切换到一个完全自由的 GNU/Linux 发行版的可能性

### ISSUE THREAD

**Issue by KenOokamiHoro** [KenOokamiHoro/it_have_not_get_a_name_yet#5]
于是有可能嘛  \_(:з」∠)\_ <s>总感觉 Debian 没那么清真……</s>

**Comment by BruceZhang1993** [comment]
切换到 BSD 嘿嘿嘿

**Comment by KenOokamiHoro** [comment]
@BruceZhang1993 兔兔过分了啊😂而且那个也不是GNU/Linux（

**Comment by KenOokamiHoro** [comment]
@OriginCode 想过，但是难度略高啊😂

**Comment by OriginCode** [comment]
@KenOokamiHoro 所以說萌狼為啥要讓人用純自由發行版呢？

**Comment by KenOokamiHoro** [comment]
@OriginCode 纯粹是个愿望问题……

**Comment by dou4cc** [comment]
先讲讲debian哪里不自由？

**Comment by dou4cc** [comment]
@KenOokamiHoro 我不认同GNU对自由操作系统的界定。为了推广自由软件把不自由软件从软件库移除是审查、手段违背目的。

**Comment by KenOokamiHoro** [comment]
暂时放弃。
